import { settings } from "./config.ts";
import { assetExists, createKnowledgeAsset, discardDraft, discardDraftIfPresent, graphsWithPredicate, verifyShared } from "./dkg.ts";
import { RDF_TYPE, bool, date, iri, str, type TripleSpec } from "./ttl.ts";

/*
 * Every approved post becomes its own sealed Journey Knowledge Asset (journey-entry-NNN).
 * Lifecycle, mirroring the DKG memory layers:
 *   candidate  : sealed private draft in Working Memory, created BEFORE the owner reviews the post
 *   approved   : draft discarded, then the same entry is created again with status "confirmed" and
 *                shared to Shared Working Memory, then read back and checked triple by triple
 *   rejected   : draft discarded; nothing ever reaches shared memory
 * Existing sealed journey assets are never edited.
 */

const TB = "https://threadbiz.ai/ontology#";

export interface EntryPlan {
  entryId: string;
  assetName: string;
  title: string;
  caption: string;
  imageUrl: string;
  imageSha256: string;
  memoryVersionUsed: string;
  explainability: string;
  runId: string;
  judgeOutcome: string;
  recordedOn: string; // YYYY-MM-DD
  /** Set when this entry supersedes an earlier sealed one (e.g. entry-001); the old asset is not modified. */
  replaces?: string;
}

/** Entries 000-008 live in the sealed weekly journey assets (journey-001..003); every pipeline post is journey-entry-NNN from 009 on. */
const FIRST_PIPELINE_ENTRY = 9;
const pad3 = (n: number) => String(n).padStart(3, "0");

/** Highest existing entry number in the journey context graph, plus one. */
export async function nextEntryId(): Promise<string> {
  const cg = settings.dkg.journeyContextGraph;
  try {
    const found = await graphsWithPredicate(cg, `${TB}entryId`);
    const numbers = found.map((f) => /^entry-(\d+)$/.exec(f.value)).filter((m): m is RegExpExecArray => !!m).map((m) => Number(m[1]));
    if (!numbers.length) throw new Error("Found no journey entries in shared memory; cannot decide the next entry id");
    return `entry-${pad3(Math.max(...numbers) + 1)}`;
  } catch (err: any) {
    console.warn(`  (entry-id discovery query failed: ${String(err.message).slice(0, 140)}; checking journey-entry-NNN asset names instead)`);
    let n = FIRST_PIPELINE_ENTRY;
    while (n < 500 && (await assetExists(`journey-entry-${pad3(n)}`, cg))) n++;
    return `entry-${pad3(n)}`;
  }
}

export function entryTriples(plan: EntryPlan, status: "candidate" | "confirmed"): TripleSpec[] {
  const s = `https://threadbiz.ai/journey/${settings.businessId}/${plan.entryId}`;
  const out: TripleSpec[] = [
    { s, p: RDF_TYPE, o: iri(`${TB}JourneyEntry`) },
    { s, p: `${TB}entryId`, o: str(plan.entryId) },
    { s, p: `${TB}businessId`, o: str(settings.businessId) },
    { s, p: `${TB}entryType`, o: str("content-generated") },
    { s, p: `${TB}title`, o: str(plan.title) },
    { s, p: `${TB}description`, o: str("Weekly social post (caption and image) generated by the ThreadBiz pipeline from the Business Memory and Improvement Memory named below.") },
    { s, p: `${TB}caption`, o: str(plan.caption) },
    { s, p: `${TB}dateOccurred`, o: date(plan.recordedOn) },
    { s, p: `${TB}dateRecorded`, o: date(plan.recordedOn) },
    { s, p: `${TB}canBeUsedPublicly`, o: bool(true) },
    { s, p: `${TB}sourceType`, o: str("livepeer-agent-generation") },
    { s, p: `${TB}sourceReference`, o: str(plan.imageUrl) },
    { s, p: `${TB}imageSha256`, o: str(plan.imageSha256) },
    { s, p: `${TB}status`, o: str(status) },
    { s, p: `${TB}memoryVersionUsed`, o: str(plan.memoryVersionUsed) },
    { s, p: `${TB}explainability`, o: str(plan.explainability) },
    { s, p: `${TB}runId`, o: str(plan.runId) },
    { s, p: `${TB}judgeOutcome`, o: str(plan.judgeOutcome) },
  ];
  if (plan.replaces) out.push({ s, p: `${TB}replaces`, o: str(plan.replaces) });
  return out;
}

export async function planEntry(p: Omit<EntryPlan, "entryId" | "assetName">): Promise<EntryPlan> {
  const entryId = await nextEntryId();
  return { ...p, entryId, assetName: `journey-${entryId}` };
}

/** Creates the private, sealed candidate draft in Working Memory. */
export async function stageCandidate(plan: EntryPlan) {
  const cg = settings.dkg.journeyContextGraph;
  await discardDraftIfPresent(plan.assetName, cg); // leftover draft from an interrupted earlier run
  return createKnowledgeAsset({ name: plan.assetName, contextGraph: cg, triples: entryTriples(plan, "candidate"), share: false });
}

/** Owner approved: replace the candidate draft with the confirmed entry, share it, and verify it. */
export async function approveEntry(plan: EntryPlan) {
  const cg = settings.dkg.journeyContextGraph;
  await discardDraftIfPresent(plan.assetName, cg);
  const triples = entryTriples(plan, "confirmed");
  const created = await createKnowledgeAsset({ name: plan.assetName, contextGraph: cg, triples, share: true });
  const verified = await verifyShared(plan.assetName, cg, triples);
  return { assetName: plan.assetName, entryId: plan.entryId, kaNumber: verified.kaNumber || created.kaNumber, triples: verified.tripleCount, status: "confirmed" as const };
}

/** Owner rejected: discard the candidate draft. Nothing was ever shared. */
export async function rejectEntry(plan: EntryPlan): Promise<boolean> {
  try {
    await discardDraft(plan.assetName, settings.dkg.journeyContextGraph);
    return true;
  } catch {
    return false;
  }
}

export function explain(o: {
  memoryAsset: string;
  entryRef: string;
  improvementAsset: string | null;
  lessonsCited: string[];
  memoryFieldsUsed: string[];
  rounds: number;
  judgeOutcome: string;
  ctaAddedByCode: boolean;
}): string {
  const parts = [
    `Generated from ${o.memoryAsset} and journey entry ${o.entryRef}${o.improvementAsset ? `, following the owner's lessons in ${o.improvementAsset}` : ""}.`,
    o.memoryFieldsUsed.length ? `Business Memory fields the writer reported using: ${o.memoryFieldsUsed.join(", ")}.` : "",
    o.lessonsCited.length ? `Owner lessons the writer cited as applied: ${o.lessonsCited.join(", ")}.` : "",
    `Judged by separate Livepeer models: ${o.judgeOutcome} (${o.rounds} round${o.rounds === 1 ? "" : "s"}).`,
    o.ctaAddedByCode ? "The closing pre-order sentence was added by code from a fixed, memory-grounded fallback." : "",
    "Confirmed only after the owner approved the caption and image.",
  ];
  return parts.filter(Boolean).join(" ");
}
